[package]
name = "sms_db"
version = "0.1.0"
edition = "2021"


[dependencies]
serde = { version = "1.0.189", features = ["derive"] }
surrealdb = { version = "1.0.0", features = ["kv-speedb"] }
tokio = { version = "1.33.0", features = ["macros", "rt-multi-thread"] }
