[package]
name = "sms_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
sms_api = { path = "../sms_api" }
sms_db = { path = "../sms_db" }
tokio = "1.32.0"
clap = { version = "4.4", features = ["derive"] }

[dev-dependencies]
sms_api = { path = "../sms_api", features = ["sms_mock_api"] }
